App:
    # path    
    path: /servers/develop/twitterparty2
    pathLog: /var/log/twitterparty2
    # url
    url: http://dev2.twitterparty.quodis.com
    # enable logs 
    logEnabled: 1
Store:
    url: http://dev2.twitterparty.quodis.com/store
    path: /servers/develop/twitterparty2/public/store
    filePermissions: 664
    dirPermissions: 775
    group: quodis
Data:
    path: /servers/data/twitterparty2
    filePermissions: 664
    dirPermissions: 775
    group: quodis
Config:
    filePermissions: 664
    group: quodis
Twitter:
    urlSearch: "http://search.twitter.com/search.json"
    terms: "#fx4 OR #ff4 OR #teamfirefox"
    rpp: 100
    pageLimit: 30
    timeout:
        apiCall: 5
        imgFile: 1
Mosaic:
    logoFile: assets/logo-48x47.png
    reducedFile: assets/logo-reduced-48x47.png
    defaultPic: assets/default48x48.png
    configFile: config/mosaic-48x47.config.php
    cols: 48
    rows: 47
    tileSize: 12
    colorDepth: 16
    internalComposite: 0
Jobs:
    twitter-search:
        hasCronSchedule: 1
        period: 10
    image-process:
        hasCronSchedule: 1
        period: 1
        dbLimit: 100
        imgLimit: 1000
    mosaic-build:
        hasCronSchedule: 1
        period: 5
Cache:
    enabled: 0
    TTL:
        mosaicConfig: 2000 
        tweetIds: 200
        index: 30
        poll: 15
    servers:
        - host: localhost
          port: 11211
Db:
    connection:
        host: localhost
        name: twitterparty2
        user: twitterparty2
        pass: twitterparty2
UI:
    gaEnabled: "0"
    gaId: ""
    title: "Firefox 4 Twitter Party"
    keywords: "Mozilla,Firefox, Firefox 4, Collage, Twitter, Tweet"
    description: "Firefox 4 Twitter Party is a visualization of Firefox 4 activity on Twitter. It is an experiment with exclusively open web tools and technologies."
    minified: 0
    js: 
        general: "/assets/js/general.js?v=1"
        config: "/assets/js/config.js?v=1"
        dashboard: "/assets/js/dashboard.js?v=1"
        minified: "/assets/js/party-min.js?v=1"
    js-config:
        grid: "/config/grid.js?v=1"
    css:
        main: "/assets/css/ftp.css?v=1"
        mosaic: "/assets/css/mosaic.css?v=1"
        dashboard: "/assets/css/dashboard.css?v=1"
        minified: "/assets/css/party-min.css?v=1"
    pollLimit: 100
    resultsLimit: 100
    options:
        store_url: http://dev2.twitterparty.quodis.com/store
        short_stat_interval: 3000
